### ISSUE TITLE
Doppelte Abfrage nötig?

### ISSUE THREAD

**Issue by LeonSchererTuK** [wertania/elearning-content-editor#45]
@wertania Ist es hier nötig, den Documents Store nochmals zu initialisieren? Das geschieht schon in der Parent-Komponente `DocumentsView.vue` und wirft nun einen Fehler, weil der Request zweimal feuert und einer davon abgebrochen wird.

https://github.com/wertania/elearning-content-editor/blame/fba8e8e49ed420da847a35e79ad1438af614de96/editor/src/views/DocumentEditor.vue#L408

**Comment by LeonSchererTuK** [comment]
@wertania Hat sich erledigt.

**Comment by wertania** [comment]
@LeonSchererTuK  
das kann auch Editor hinzufügen beim initialisieren:

<img width="722" alt="image" src="https://github.com/wertania/elearning-content-editor/assets/68941720/029c6ef9-ce18-415a-ae34-3589fc58895d">
